$ANSIBLE_VAULT;1.1;AES256
31353837646133356235653235613433313865633736666435376530363465333433333733303835
3564646165356433303038346631323165666165313864310a343264383435393037396238613337
37663663356463633863393765383965303233333561643961393833316565636366643837366633
6334636235616564380a663137613031316361643130346332316565366663323838643133396635
37636262643661636563336564303238353137623939663331373339366539383830313034643332
38636265303363653865383262323063626535663832663266633538633632393733353465613430
38643539326263633637653531646532376630303365303437343363373061313863386438633636
34623830656531396531
